modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "copyblockid"
version = "1.1.0"
displayName = "CopyBlockId"
authors = "wodichka"
logoFile = "icon.png"
description = '''Lightweight client-side NeoForge utility: press Ctrl+C to copy hovered inventory item IDs, JEI/REI ingredient IDs, fluid IDs, and configurable targeted block or entity IDs straight to the clipboard.'''

[[dependencies."copyblockid"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.230,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."copyblockid"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"
